kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cnwan-operator-manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: cnwan-operator-service-account
    namespace: cnwan-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnwan-operator-manager-role
