kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cnwan-operator-rolebinding
  namespace: cnwan-operator-system
subjects:
  - kind: ServiceAccount
    name: cnwan-operator-service-account
    namespace: cnwan-operator-system
roleRef:
  kind: Role
  name: cnwan-operator-role
  apiGroup: rbac.authorization.k8s.io