kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cnwan-operator-cluster-role
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
      - services
