name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, edited, reopened, synchronize]

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: install go
        id: install-go
        uses: actions/setup-go@master
        with:
          go-version: "^1.13.x"

      - name: checkout code
        id: checkout-code
        uses: actions/checkout@master

      - name: install kubebuilder
        id: install-kubebuilder
        run: |
            os=$(go env GOOS)
            arch=$(go env GOARCH)
            curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
            sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
            export PATH=$PATH:/usr/local/kubebuilder/bin
      - id: test-code
        name: test
        run: make test
