name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, edited, reopened, synchronize]

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: install go
        id: install-go
        uses: actions/setup-go@master
        with:
          go-version: "^1.13.x"

      - name: checkout code
        id: checkout-code
        uses: actions/checkout@master

      - name: install kubebuilder
        id: install-kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1
        with:
          version: 2.3.1

      - id: test-code
        name: test
        run: make test
